In [4]:
import numpy as np
#1
n = 10
ve = np.arange(n) 
ve

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#2
ve = np.zeros(4)
fv = [5]
ze = np.zeros(n-5)
arr = np.append(ve, fv)
arr = np.append(arr, ze)
arr

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

In [8]:
#3 
vc = np.arange(10,50,1)
vc

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
#4
vcsr = np.sort(vc)[::-1]
vcsr 

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [10]:
#5 
vc = np.arange(9).reshape(3, 3)
vc

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
#6
i = 0
vc = np.array([1,2,0,0,4,0] )
a = np.array([0,0,0,0,0,0,])
b = vc > a
b
c = np.where(vc>a)
c

(array([0, 1, 4], dtype=int64),)

In [35]:
#7
np.identity(n=3, dtype=np.int8)	

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [40]:
#8
r = np.random.seed(seed=1000)	 # 시드로 난수 생성 초기값 지정

r = np.random.uniform(0, 1, 9).reshape(3,3)
r

array([[0.65358959, 0.11500694, 0.95028286],
       [0.4821914 , 0.87247454, 0.21233268],
       [0.04070962, 0.39719446, 0.2331322 ]])

In [43]:
#9
np.max(r), np.min(r)

(0.9502828643490245, 0.040709624769089126)

In [44]:
#10
r.mean(axis=0)

array([0.39216354, 0.46155865, 0.46524925])

In [45]:
r.mean(axis=1)

array([0.5729598 , 0.52233287, 0.22367876])